name: My Jekyll Website

plugins:
  - jekyll-datapage-generator

page_gen:
  - data: 'meta'
    template: 'reader'
    name: 'id'
    dir: ''

page_gen:
  - data: 'meta'
    template: 'content.js'
    name: 'id'
    dir: 'build/js'
