esperanto:
    booknames: Genezo, Eliro, Levidoj, Nombroj, Readmono, Josuo, Juĝistoj, Ruth, 1 Samuel, 2 Samuel, 1 Reĝoj, 2 Reĝoj, 1 Kronikoj, 2 Kronikoj, Ezra, Nehemiah, Libro de Ester, Ijobo, Psalmoj, devizo, Ekleziulo, Kanto de Kantoj, Libro de Jesaja, Jeremia, Lamentoj pri Jeremia, Libro de Ezekiel, Daniel, Hosea, Libro de Joel, Libro de Amos, Obadiah, Jonah, Miicaa, Libro de Nahum, Habakuk, Cephaniah, Haggai, Libro de Zehxarja, Malachi, Evangelio laŭ Mateo, Evangelio de Marko, Luko, Evangelio de Johano, Agoj de la Apostoloj, Romanoj, 1 Korintanoj, 2 Korintanoj, Galatoj, Efesanoj, Filipianoj, Kolosianoj, Tesalonikanoj, 2 Tesalonikanoj, 1 Timoteo, 2 Timoteo, Tito, Filemono, Hebrea, Libro de Jakobo, Unua Peter, 2 Petro, Libro de 1 Johano, La Libro de Johano Du, John's Reference, Jude, Revelacio
    locnumnames: 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150
    locchapterpref: "Ĉapitro "
    locchaptersuff: " "
    locprev: Prev
    locnext: Next
    locformval: Iri! →
    locpsalmcountword: ""
    locpsalmbookname: "Psalmoj"
    locsearchquery: "Serĉu Skribojn ─ "
    locspacingpref: ": "
chinese:
    booknames: 創世記, 出埃及記, 利未記, 民數記, 申命記, 約書亞記, 士師記, 路得記, 撒母耳記上, 撒母耳記下, 列王紀上, 列王紀下, 歷代志上, 歷代志下, 以斯拉記, 尼希米記, 以斯帖記, 約伯記, 詩篇, 箴言, 傳道書, 雅歌, 以賽亞書, 耶利米書, 耶利米哀歌, 以西結書, 但以理書, 何西阿書, 約珥書, 阿摩司書, 俄巴底亞書, 約拿書, 彌迦書, 那鴻書, 哈巴谷書, 西番雅書, 哈該書, 撒迦利亞書, 瑪拉基書, 馬太福音, 馬可福音, 路加福音, 約翰福音, 使徒行傳, 羅馬書, 哥林多前書, 哥林多後書, 加拉太書, 以弗所書, 腓利比書, 歌羅西書, 帖撒羅尼迦前書, 帖撒羅尼迦後書, 提摩太前書, 提摩太後書, 提多書, 腓利門書, 希伯來書, 雅各書, 彼得前書, 彼得後書, 約翰壹書, 約翰貳書, 約翰參書, 猶大書, 啟示錄
    locnumnames: 一,二,三,四,五,六,七,八,九,十,十一,十二,十三,十四,十五,十六,十七,十八,十九,二十,二十一,二十二,二十三,二十四,二十五,二十六,二十七,二十八,二十九,三十,三十一,三十二,三十三,三十四,三十五,三十六,三十七,三十八,三十九,四十,四十一,四十二,四十三,四十四,四十五,四十六,四十七,四十八,四十九,五十,五十一,五十二,五十三,五十四,五十五,五十六,五十七,五十八,五十九,六十,六十一,六十二,六十三,六十四,六十五,六十六,六十七,六十八,六十九,七十,七十一,七十二,七十三,七十四,七十五,七十六,七十七,七十八,七十九,八十,八十一,八十二,八十三,八十四,八十五,八十六,八十七,八十八,八十九,九十,九十一,九十二,九十三,九十四,九十五,九十六,九十七,九十八,九十九,一百,一百零一,一百零二,一百零三,一百零四,一百零五,一百零六,一百零七,一百零八,一百零九,一百一十,一百十一,一百十二,一百十三,一百十四,一百十五,一百十六,一百十七,一百十八,一百十九,一百二十,一百二十一,一百二十二,一百二十三,一百二十四,一百二十五,一百二十六,一百二十七,一百二十八,一百二十九,一百三十,一百三十一,一百三十二,一百三十三,一百三十四,一百三十五,一百三十六,一百三十七,一百三十八,一百三十九,一百四十,一百四十一,一百四十二,一百四十三,一百四十四,一百四十五,一百四十六,一百四十七,一百四十八,一百四十九,一百五十
    locprev: 上一章
    locnext: 下一章
    locformval: 閱讀
    locchapterpref: "第 "
    locchaptersuff: " 章"
    locpsalmpref: "章"
    locpsalmcountword: "篇"
    locpsalmbookname: "詩篇"
    locsearchquery: "搜尋經文─"
    locspacingpref: ""
