esperanto:
    booknames: Genezo, Eliro, Levidoj, Nombroj, Readmono, Josuo, Juĝistoj, Ruth, 1 Samuel, 2 Samuel, 1 Reĝoj, 2 Reĝoj, 1 Kronikoj, 2 Kronikoj, Ezra, Nehemiah, Libro de Ester, Ijobo, Psalmo, devizo, Ekleziulo, Kanto de Kantoj, Libro de Jesaja, Jeremia, Lamentoj pri Jeremia, Libro de Ezekiel, Daniel, Hosea, Libro de Joel, Libro de Amos, Obadiah, Jonah, Miicaa, Libro de Nahum, Habakuk, Cephaniah, Haggai, Libro de Zehxarja, Malachi, Evangelio laŭ Mateo, Evangelio de Marko, Luko, Evangelio de Johano, Agoj de la Apostoloj, Romanoj, 1 Korintanoj, 2 Korintanoj, Galatoj, Efesanoj, Filipianoj, Kolosianoj, Tesalonikanoj, 2 Tesalonikanoj, 1 Timoteo, 2 Timoteo, Tito, Filemono, Hebrea, Libro de Jakobo, Unua Peter, 2 Petro, Libro de 1 Johano, La Libro de Johano Du, John's Reference, Jude, Revelacio
    locchapterpref: "ĉapitro  "
    locchaptersuff: " "
    locprev: Prev
    locnext: Next
    locformval: locformval
chinese:
    booknames: 創世記, 出埃及記, 利未記, 民數記, 申命記, 約書亞記, 士師記, 路得記, 撒母耳記上, 撒母耳記下, 列王紀上, 列王紀下, 歷代志上, 歷代志下, 以斯拉記, 尼希米記, 以斯帖記, 約伯記, 詩篇, 箴言, 傳道書, 雅歌, 以賽亞書, 耶利米書, 耶利米哀歌, 以西結書, 但以理書, 何西阿書, 約珥書, 阿摩司書, 俄巴底亞書, 約拿書, 彌迦書, 那鴻書, 哈巴谷書, 西番雅書, 哈該書, 撒迦利亞書, 瑪拉基書, 馬太福音, 馬可福音, 路加福音, 約翰福音, 使徒行傳, 羅馬書, 哥林多前書, 哥林多後書, 加拉太書, 以弗所書, 腓利比書, 歌羅西書, 帖撒羅尼迦前書, 帖撒羅尼迦後書, 提摩太前書, 提摩太後書, 提多書, 腓利門書, 希伯來書, 雅各書, 彼得前書, 彼得後書, 約翰壹書, 約翰貳書, 約翰參書, 猶大書, 啟示錄
    locprev: 上一章
    locnext: 下一章
    locformval: 閱讀
    locchapterpref: "第 "
    locchaptersuff: " 章"
