- id: esperanto
  source: Esperanto__Esperanto__esperanto__LTR.txt
  booknames: Genezo, Eliro, Levidoj, Nombroj, Readmono, Josuo, Juĝistoj, Rut, I Samuel, II Samuel, I Reĝoj, II Reĝoj, I Kroniko, II Kroniko, Ezdra, Neĥemja, Ester, Ijob, Psalmaro, Sentencoj, Predikanto, Alta Kanto, Jesaja, Jeremia, Plorkanto, Jeĥezkel, Danielo, Hoŝea, Joel, Amos, Obadja, Jona, Miĥa, Naĥum, Ĥabakuk, Cefanja, Ĥagaj, Zeĥarja, Malaĥi, Mateo, Marko, Luko, Johano, La Agoj de la Apostoloj, Romanoj, I Korintanoj, II Korintanoj, Galatoj, Efesanoj, Filipianoj, Koloseanoj, I Tesalonikanoj, II Tesalonikanoj, I Timoteo, II Timoteo, Tito, Filemon, Hebreoj, Jakobo, I Petro, II Petro, I Johano, II Johano, III Johano, Judas, Apokalipso
  locchapterpref: "Ĉapitro "
  locchaptersuff: " "
  locformval: Navigi! →
  locpsalmcountword: ""
  locpsalmbookname: "Psalmoj"
  locsearchquery: "Serĉu Skribojn ─ "
  locspacingpref: ": "
  licence: "*L.L.Zamenhof* (1915), **Malnova Testamento**. *Brita kaj Alilanda Biblia Societo* (1963), **La Nova Testamento de
nia Sinjoro kaj Savanto Jesuo Kristo**."
- id: chinese
  source: Chinese__Union_Traditional__cut__LTR.txt
  booknames: 創世記, 出埃及記, 利未記, 民數記, 申命記, 約書亞記, 士師記, 路得記, 撒母耳記上, 撒母耳記下, 列王紀上, 列王紀下, 歷代志上, 歷代志下, 以斯拉記, 尼希米記, 以斯帖記, 約伯記, 詩篇, 箴言, 傳道書, 雅歌, 以賽亞書, 耶利米書, 耶利米哀歌, 以西結書, 但以理書, 何西阿書, 約珥書, 阿摩司書, 俄巴底亞書, 約拿書, 彌迦書, 那鴻書, 哈巴谷書, 西番雅書, 哈該書, 撒迦利亞書, 瑪拉基書, 馬太福音, 馬可福音, 路加福音, 約翰福音, 使徒行傳, 羅馬書, 哥林多前書, 哥林多後書, 加拉太書, 以弗所書, 腓利比書, 歌羅西書, 帖撒羅尼迦前書, 帖撒羅尼迦後書, 提摩太前書, 提摩太後書, 提多書, 腓利門書, 希伯來書, 雅各書, 彼得前書, 彼得後書, 約翰壹書, 約翰貳書, 約翰參書, 猶大書, 啟示錄
  locnumnames: 一, 二, 三, 四, 五, 六, 七, 八, 九, 十, 十一, 十二, 十三, 十四, 十五, 十六, 十七, 十八, 十九, 二十, 二十一, 二十二, 二十三, 二十四, 二十五, 二十六, 二十七, 二十八, 二十九, 三十, 三十一, 三十二, 三十三, 三十四, 三十五, 三十六, 三十七, 三十八, 三十九, 四十, 四十一, 四十二, 四十三, 四十四, 四十五, 四十六, 四十七, 四十八, 四十九, 五十, 五十一, 五十二, 五十三, 五十四, 五十五, 五十六, 五十七, 五十八, 五十九, 六十, 六十一, 六十二, 六十三, 六十四, 六十五, 六十六, 六十七, 六十八, 六十九, 七十, 七十一, 七十二, 七十三, 七十四, 七十五, 七十六, 七十七, 七十八, 七十九, 八十, 八十一, 八十二, 八十三, 八十四, 八十五, 八十六, 八十七, 八十八, 八十九, 九十, 九十一, 九十二, 九十三, 九十四, 九十五, 九十六, 九十七, 九十八, 九十九, 一百, 一百零一, 一百零二, 一百零三, 一百零四, 一百零五, 一百零六, 一百零七, 一百零八, 一百零九, 一百一十, 一百十一, 一百十二, 一百十三, 一百十四, 一百十五, 一百十六, 一百十七, 一百十八, 一百十九, 一百二十, 一百二十一, 一百二十二, 一百二十三, 一百二十四, 一百二十五, 一百二十六, 一百二十七, 一百二十八, 一百二十九, 一百三十, 一百三十一, 一百三十二, 一百三十三, 一百三十四, 一百三十五, 一百三十六, 一百三十七, 一百三十八, 一百三十九, 一百四十, 一百四十一, 一百四十二, 一百四十三, 一百四十四, 一百四十五, 一百四十六, 一百四十七, 一百四十八, 一百四十九, 一百五十
  locformval: 閱讀
  locchapterpref: "第 "
  locchaptersuff: " 章"
  locpsalmpref: "章"
  locpsalmcountword: "篇"
  locpsalmbookname: "詩篇"
  locsearchquery: "搜尋經文─"
  locspacingpref: ""
  licence: "*Frederick W. Baller, C. Goodrich, Calvin Wilson Mateer, Spencer Lewis, and George Sydney Owen* (1919). **Chinese Union Version**."
- id: swedish
  source: Swedish__Swedish_(1917)__swedish__LTR.txt
  booknames: 1 Mosebok, 2 Mosebok, 3 Mosebok, 4 Mosebok, 5 Mosebok, Josua, Domarboken, Rut, 1 Samuelsboken, 2 Samuelsboken, 1 Kungaboken, 2 Kungaboken, 1 Krönikeboken, 2 Krönikeboken, Esra, Nehemja, Ester, Job, Psaltaren, Ordspråksboken, Predikaren, Höga Visan, Jesaja, Jeremia, Klagovisorna, Hesekiel, Daniel, Hosea, Joel, Amos, Obadja, Jona, Mika, Nahum, Habackuk, Sefanja, Haggai, Sakaria, Malaki, Matteus, Markus, Lukas, Johannes, Apostlagärningarna, Romarbrevet, 1 Korinthierbrevet, 2 Korinthierbrevet, Galaterbrevet, Efesierbrevet, Filipperbrevet, Kolosserbrevet, 1 Thessalonikerbrevet, 2 Thessalonikerbrevet, 1 Timotheosbrevet, 2 Timotheosbrevet, Titusbrevet, Filemonbrevet, Hebreerbrevet, Jakobsbrevet, 1 Petrusbrevet, 2 Petrusbrevet, 1 Johannesbrevet, 2 Johannesbrevet, 3 Johannesbrevet, Judasbrevet1, Uppenbarelseboken
  locchapterpref: "Kapitel "
  locchaptersuff: " "
  locformval: Gå! →
  locpsalmcountword: ""
  locpsalmbookname: "Psaltaren"
  locsearchquery: "Sök i Skrifterna ─ "
  locspacingpref: ": "
  licence: "*Evangeliska fosterlandsstiftelsens bokförlag* (1917), **Bibeln eller Den Heliga Skrift**. Gamla och Nya Testamentet de Kanoniska Böckerna."
- id: indonesian
  source: indonesian.txt
  booknames: Kejadian, Keluaran, Imamat, Bilangan, Ulangan, Yosua, Hakim-hakim, Rut, 1 Samuel, 2 Samuel, 1 Raja-raja, 2 Raja-raja, 1 Tawarikh, 2 Tawarikh, Ezra, Nehemia, Ester[i], Ayub, Mazmur, Amsal, Pengkhotbah, Kidung Agung, Yesaya, Yeremia, Ratapan, Yehezkiel, Daniel[p], Hosea, Yoel, Amos, Obaja, Yunus, Mikha, Nahum, Habakuk, Zefanya, Hagai, Zakharia, Maleakhi, Matius, Markus, Lukas, Yohanes, Kisah Para Rasul, Roma, 1 Korintus, 2 Korintus, Galatia, Efesus, Filipi, Kolose, 1 Tesalonika, 2 Tesalonika, 1 Timotius, 2 Timotius, Titus, Filemon, Ibrani, Yakobus, 1 Petrus, 2 Petrus, 1 Yohanes, 2 Yohanes, 3 Yohanes, Yudas, Wahyu
  locchapterpref: "Bab "
  locchaptersuff: " "
  locformval: Pergi! →
  locpsalmcountword: ""
  locpsalmbookname: "Mazmur"
  locsearchquery: "Cari di dalam Tulisan suci ─ "
  locspacingpref: ": "
  licence: "*Lembaga Alkitab Indonesia* (1985), **Alkitab Kabar Baik** atau Alkitab Bahasa Indonesia Sehari-hari (BIS)."
- id: french
  source: français.csv
  booknames: La Genèse, L’Exode, Le Lévitique, Les Nombres, Le Deutéronome, Josué, Les Juges, 1 Samuel, 2 Samuel, 1 Rois, 2 Rois, Isaïe, Jérémie, Ézéchiel, Osée, Joël, Amos, Obadia, Jonas, Michée, Nahoum, Habacuc, Cephania, Haggaï, Zacharie, Malachie, Les Psaumes, Les Proverbes, Job, Le Cantique des cantiques, Ruth, Les Lamentations, L’Ecclésiaste ou Qohélet, Esther, Daniel, Ezra, Néhémie, 1 Chroniques, 2 Chroniques
  locchapterpref: "Chapitre "
  locchaptersuff: " "
  locformval: Y aller ! →
  locpsalmcountword: ""
  locpsalmbookname: "Psaumes"
  locsearchquery: "Rechercher dans les Écritures ─ "
  locspacingpref: ": "
  licence: "*Zadoc Kahn* (1899), **La Bible** (2 vols.), Libraire-éditeur A. Durlacher."
